### ISSUE TITLE
ETL link

### ISSUE THREAD

**Issue by ferrisoxide** [dpaluy/awesome-rails#5]
First off - super awesome curated list. 

_Very_ minor bug. The 'ETL' link in the table of contents should point here (currently doesn't work):

https://github.com/dpaluy/awesome-rails#etl---extract-transform-load

Thank you for all your work btw. Well done.

**Comment by dpaluy** [comment]
Thanks, fixed: https://github.com/dpaluy/awesome-rails/commit/15b99c6ddb945fc5f82517ccdb39dd1558213a1e
