### ISSUE TITLE
Where to put boilerplate?

### ISSUE THREAD

**Issue by simonfranzen** [dpaluy/awesome-rails#9]
Hey, I have created a boilerplate for rails6 (devise+graphql) -> https://github.com/zauberware/rails-devise-graphql

Where can I add this here in the Readme?

**Comment by dpaluy** [comment]
@simonfranzen Let's create a new section `Boilerplates`. Can you please create a PR?

**Comment by simonfranzen** [comment]
PR is open https://github.com/dpaluy/awesome-rails/pull/10 :)
